CREATE TABLE app_role (
    id BIGSERIAL PRIMARY KEY,
    name CHARACTER VARYING(50)
);

CREATE TABLE app_account (
    id BIGSERIAL PRIMARY KEY,
    email CHARACTER VARYING(255) UNIQUE NOT NULL,
    password CHARACTER VARYING(1000) NOT NULL
);

CREATE TABLE app_user (
    id BIGSERIAL PRIMARY KEY,
    first_name CHARACTER VARYING(100) NOT NULL,
    last_name CHARACTER VARYING(100) NOT NULL,
    image CHARACTER VARYING(255),
    account_id BIGINT UNIQUE NOT NULL REFERENCES app_account(id),
    role_id BIGINT NOT NULL REFERENCES app_role(id)
);

INSERT INTO app_role VALUES (1, 'ADMIN');
INSERT INTO app_role VALUES (2, 'USER');
INSERT INTO app_role VALUES (3, 'DOCTOR');